Markup
Keisuke-Awa/chat-space pull request #3
Opened 2017-10-16 13:30 UTC by Keisuke-Awa

# WHAT
チャット画面のhtml/scssのマークアップ

# WHY
今後裏の機能を作っていくのに必要なため。
<img width="1440" alt="2017-10-16 22 29 52" src="https://user-images.githubusercontent.com/26059040/31614510-9c040994-b2c1-11e7-9bfa-d195dc3efc65.png">
<img width="1440" alt="2017-10-16 22 30 05" src="https://user-images.githubusercontent.com/26059040/31614511-9c2d0362-b2c1-11e7-8f56-827e03042b99.png">

2017-10-16 14:31 UTC, offich requested changes
修正シクヨロ

2017-10-16 14:31 UTC, r-ume commented on app/controllers/messages_controller.rb
> +  def index; end
GOOD
この書き方を知っているのGOOD

2017-10-16 14:31 UTC, r-ume commented on config/routes.rb
> +  resources :messages, only: :index
これから、resourcesでいろいろと書いていくから、修正しなくてもいいけど、これだと、rootと重複していることだけ知っておいて。

2017-10-16 14:31 UTC, r-ume commented on test/controllers/messages_controller_test.rb
> +require 'test_helper'
これは、このPRとは関係ないから、このPRから消しておいてくれるとー

2017-10-16 14:31 UTC, r-ume commented on app/assets/stylesheets/messages.scss
> +  background-color: #2f3e51;
せっかく、上で `$blue` って変数を使っているから、ここも変数で定義しようかー。

2017-10-16 14:31 UTC, r-ume commented on app/assets/stylesheets/messages.scss
> +    border-bottom: solid 0.1px #eeeeee;
ここ以外の色も、全部変数で定義してくれるとー。

2017-10-16 14:31 UTC, r-ume commented on app/assets/stylesheets/messages.scss
> +      // display: table;
ここのコメントは消して置いて。

2017-10-16 14:31 UTC, r-ume commented on app/helpers/messages_helper.rb
> +module MessagesHelper
helperは、よほどのことがない限り、使わない方針でお願いー

2017-10-16 15:36 UTC, Keisuke-Awa commented on app/assets/stylesheets/messages.scss
> +  background-color: #2f3e51;
修正しました

2017-10-16 15:36 UTC, Keisuke-Awa commented on app/assets/stylesheets/messages.scss
> +    border-bottom: solid 0.1px #eeeeee;
修正しました

2017-10-16 15:37 UTC, Keisuke-Awa commented on app/assets/stylesheets/messages.scss
> +      // display: table;
修正しました

2017-10-16 15:37 UTC, Keisuke-Awa commented on app/helpers/messages_helper.rb
> +module MessagesHelper
了解です

2017-10-16 15:37 UTC, Keisuke-Awa commented on config/routes.rb
> +  resources :messages, only: :index
了解です！

2017-10-16 15:42 UTC, Keisuke-Awa commented on test/controllers/messages_controller_test.rb
> +require 'test_helper'
PRから消す場合どうすればいいでしょうか？？

2017-10-17 00:43 UTC, r-ume commented
`_variable.scss` というファイルに、色の変数を書いていこうか。せっかく、変数定義して、`application.scss` で読み込んでいるから。

2017-10-17 01:02 UTC, r-ume commented
1. あと、コミットメッセージは、具体的に `何をしたか` を書くようにしようか。
 - 「最終調整をした。」っていうメッセージは、正直パッと見て、何をしているのか、読み手にはわからないから、具体的にどこをどう調整したかって書かないと、今後、バグが出て来たときに、コミットメッセージで原因を追求しづらくなるから。

2. PRのタイトルやWHATやWHY、ブランチ名も、もっと具体的なほうがいいね。
 - マークアップってつけたいのは、わかるけど、このPRは、チャット画面のPRだから、ブランチ名は、`feature/chat_screen_design` とかだとわかりやすいなと思う。
 - `WHY` も `今後裏の機能を作っていくのに必要なため。` っていう理由もあまり印象が良くない。`裏の機能`って何？ってなるから、`メッセージ送信の下準備のため` とかだといいかなと思う。

2017-10-17 07:16 UTC, r-ume commented
ちゃんとデザインがしっかりしているなら、LGTM

2017-10-17 07:21 UTC, merged