devise/user用ビューファイルの作成
Keisuke-Awa/chat-space pull request #6
Opened 2017-10-19 14:44 UTC by Keisuke-Awa

# WHY
ユーザーのsign_up/sign_in機能を作成するにあたり、ビューが必要なため。

# WHAT
- devise/user用のviewファイルの自動作成
- 事前にcloneしたファイルとの一部ファイルの差し替え
- 不要なビューファイルの削除
- users.scssの配置・インポート
- 不要なルーティングの削除

## users/sign_upのビュー
<img width="1440" alt="2017-10-19 22 04 14" src="https://user-images.githubusercontent.com/26059040/31776740-52652da0-b527-11e7-8c65-06c4385565b1.png">

## users/sign_inのビュー
<img width="1440" alt="2017-10-19 22 04 27" src="https://user-images.githubusercontent.com/26059040/31776741-528d67f2-b527-11e7-89cc-ec523bf30d44.png">

2017-10-19 14:48 UTC, offich reviewed
実際に、ログインってした？

2017-10-19 14:48 UTC, r-ume commented on config/routes.rb
> +  devise_for :users, only: [:session, :registrations]
**GOOD**
onlyいいね。

2017-10-19 14:49 UTC, r-ume commented on public/assets/.sprockets-manifest-129e960afaca9fb58234422df3e78e4c.json
> +{"files":{"application-df385b4888d1fda4d5c5aff4cdc4c493c94336d47ed7b670e077b6286fd3c814.js":{"logical_path":"application.js","mtime":"2017-10-19T21:38:15+09:00","size":371753,"digest":"df385b4888d1fd
これは、cssのコンパイルファイルだから、PRから消してもらってもいい？

2017-10-19 14:55 UTC, Keisuke-Awa commented
>実際に、ログインってした？
しました！

2017-10-19 14:56 UTC, Keisuke-Awa commented on public/assets/.sprockets-manifest-129e960afaca9fb58234422df3e78e4c.json
> +{"files":{"application-df385b4888d1fda4d5c5aff4cdc4c493c94336d47ed7b670e077b6286fd3c814.js":{"logical_path":"application.js","mtime":"2017-10-19T21:38:15+09:00","size":371753,"digest":"df385b4888d1fd
凡ミスですみません、ignoreしました

2017-10-19 15:03 UTC, r-ume commented on app/assets/stylesheets/users.scss
> +    background-color: #fff;
せっかく、scssで書いているから、色は変数化しよう。他の色も変数化してくれるとー

2017-10-19 15:03 UTC, r-ume commented on app/assets/stylesheets/application.scss
>  @import "./variable";
`variable` っていう名前は、変数を定義する場所としてあっているけど、せっかくだから、`color_variables` にしようか。

2017-10-19 15:07 UTC, r-ume commented
一つ質問。`users/sign_in` のビューにグレーの`sign_up` ボタンがあるのは仕様？

2017-10-19 15:09 UTC, Keisuke-Awa commented
> 一つ質問。users/sign_in のビューにグレーのsign_up ボタンがあるのは仕様？

そこは仕様です!

2017-10-19 15:10 UTC, Keisuke-Awa commented
> 一つ質問。`users/sign_in` のビューにグレーの`sign_up` ボタンがあるのは仕様？

そこは仕様です！

2017-10-19 15:13 UTC, r-ume commented
おけー

2017-10-19 15:48 UTC, Keisuke-Awa commented
ビューは全て正常です。

2017-10-19 15:48 UTC, Keisuke-Awa commented on app/assets/stylesheets/users.scss
> +    background-color: #fff;
こちら全て_colors_variableに移しました

2017-10-19 15:48 UTC, Keisuke-Awa commented on app/assets/stylesheets/application.scss
>  @import "./variable";
variableとは別にcolors_variableを作成しました

2017-10-19 16:12 UTC, r-ume commented on app/assets/stylesheets/application.scss
>  @import "./variable";
うーん、そうなると、`variable` ファイルの必要性なくっちゃうから、何も書かないなら、消そうか。

2017-10-20 02:07 UTC, r-ume commented
一気に言わなくて、すまん。ユーザーのシードファイルも追加してもらってもいい？
（一個前のユーザーテーブルを作っているときに、言わなくてごめん。）

2017-10-20 03:19 UTC, Keisuke-Awa commented on app/assets/stylesheets/application.scss
>  @import "./variable";
消しましたー

2017-10-20 04:21 UTC, offich requested changes
修正シクヨロ〜

2017-10-20 04:21 UTC, r-ume commented on app/assets/stylesheets/application.scss
>  @import "./variable";
ここの`application.scss` からも`variable` を消してくれるとー

2017-10-20 04:21 UTC, r-ume commented on db/seeds.rb
> +  User.create(name: 'keisuke',email: 'keisuke.awa.basket@gmail.com', password: 'keisuke1027')
**THINK**
生のパスワードとか書いちゃうのは、ちょっとNGだね。オープンレポジトリだし...。あわちゃんのテスト用のやつは、自分で railsコンソールでいれて、何人かのユーザーは、Fakerなどのgemを使って入れよう。

2017-10-20 06:54 UTC, Keisuke-Awa commented on db/seeds.rb
> +  User.create(name: 'keisuke',email: 'keisuke.awa.basket@gmail.com', password: 'keisuke1027')
そのように修正しました

2017-10-20 07:04 UTC, r-ume commented
LGTM

2017-10-20 07:05 UTC, r-ume commented on db/seeds.rb
> +        password: Faker::Internet.password
**GOOD**

2017-10-20 07:07 UTC, merged