ユーザ編集機能/サインイン・サインアウトの実装
Keisuke-Awa/chat-space pull request #8
Opened 2017-10-21 02:22 UTC by Keisuke-Awa

# WHY
ユーザのログイン情報を使うあたり、サインイン・サインアウト機能が必要であり、ユーザの編集機能が必要なため。

# WHAT
- user_controllerの作成
- ルーティングの作成
- userのedit/updateアクションの定義
- ストロングパラメータの編集
- 各アクションのリダイレクト先の指定

##users/edit.html.haml
![2017-10-21 11 11 11 2](https://user-images.githubusercontent.com/26059040/31847094-a7a8a7ea-b650-11e7-8cf0-b29c20e5aa78.png)

2017-10-21 02:33 UTC, Keisuke-Awa commented
各ページへのリダイレクト・遷移の確認、ユーザ編集の挙動も問題ありません。

2017-10-21 05:15 UTC, offich requested changes
修正シクヨロ

2017-10-21 05:15 UTC, offich commented on app/controllers/users_controller.rb
> +    params[:user].permit(:name, :email)
railswayでやるなら、`params.require(:user)` かな。

2017-10-21 05:15 UTC, offich commented on app/helpers/users_helper.rb
> +module UsersHelper
何も書いていないなら、PRから外してくれるとー

2017-10-21 05:15 UTC, offich commented on app/views/messages/index.html.haml
> -%div.side-bar
あー、すまん、見逃していたね。

2017-10-21 05:15 UTC, r-ume commented on config/routes.rb
>    resources :messages, only: :index
ここは、もう被っているから、消そうか。（これから、resourcesでアクションを加えて行くから、いいと思ったけど、加えるときに、書いて）

2017-10-21 05:15 UTC, r-ume commented on app/controllers/users_controller.rb
> +
ここに、`authenticate_user!` と対応するアクションも書いてくれると

2017-10-21 05:15 UTC, r-ume commented on app/controllers/users_controller.rb
> +    current_user.update(update_params)
ここは、`@user` がいいかな。ログインしていない状態で、updateアクションが走ると、current_userがnilオブジェクトになって、よくないので。

2017-10-21 05:15 UTC, r-ume commented on app/views/users/edit.html.haml
> +      = form_for(current_user) do |f|
ここは、正直、`@user` がいいかな。
ログインしていない状態で、このページを開くとnilオブジェクトになって、エラーが発生してしまうので。
editに行くとき、該当するidのユーザーがいないときは、404のページが表示されるようにしたいから。

2017-10-22 08:11 UTC, Keisuke-Awa commented on app/controllers/users_controller.rb
> +
修正しました

2017-10-22 08:17 UTC, Keisuke-Awa commented on app/controllers/users_controller.rb
> +    current_user.update(update_params)
修正しました。同時に、set_userのメソッドを作りました。

2017-10-22 08:17 UTC, Keisuke-Awa commented on app/controllers/users_controller.rb
> +    params[:user].permit(:name, :email)
修正しました。

2017-10-22 08:18 UTC, Keisuke-Awa commented on app/helpers/users_helper.rb
> +module UsersHelper
外しました！

2017-10-22 08:25 UTC, Keisuke-Awa commented on app/views/users/edit.html.haml
> +      = form_for(current_user) do |f|
なるほど。。修正しました！

2017-10-22 08:27 UTC, Keisuke-Awa commented on config/routes.rb
>    resources :messages, only: :index
修正しました！
必要ないものは書かない、コミットしない、必要になったら書く、は本当に徹底しないといけないですね。

2017-10-22 08:43 UTC, Keisuke-Awa commented
以上修正しました。

2017-10-22 08:43 UTC, Keisuke-Awa commented
authenticate_user!やusers#edit/updateの挙動も確認済みです

2017-10-23 01:04 UTC, r-ume commented
LGTM

2017-10-23 04:24 UTC, merged